# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!


Fast vectorized computation
Efficient multi-dimensional arrays
Backbone for libraries like:
Pandas
Scikit-learn
TensorFlow
PyTorch

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    pip install numpy
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
type(my_list)

list

In [ ]:
my_list=np.array(my_list)
my_list

array([1, 2, 3])

In [ ]:
type(my_list)

numpy.ndarray

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
type(my_matrix)

list

In [ ]:
my_matrix=np.array(my_matrix)
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(my_matrix)

numpy.ndarray

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [ ]:
np.random.rand(2)

array([0.85905431, 0.15837604])

In [ ]:
np.random.rand(5,5)

array([[0.68172562, 0.78066268, 0.56972462, 0.69286417, 0.06416458],
       [0.96525474, 0.23104821, 0.63648686, 0.50674662, 0.07813365],
       [0.13916895, 0.72075517, 0.71074548, 0.1132892 , 0.91797133],
       [0.67165252, 0.74654033, 0.47849191, 0.87106457, 0.82944078],
       [0.35742563, 0.70518321, 0.52639709, 0.50025982, 0.24042773]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

The standard normal distribution is a special case of the normal distribution. For the standard normal distribution, the value of the mean is equal to zero (μ=0), and the value of the standard deviation is equal to 1 (σ=1). The random variable that possesses the standard normal distribution is denoted by z.

In [ ]:
np.random.randn(2)

array([-1.5583024 , -0.36620529])

In [ ]:
sd=np.random.randn(5,5)
sd

array([[-0.20207012,  0.23759761, -1.55518165, -1.33119386,  1.68802461],
       [ 0.39890117,  0.09031638,  0.38975942,  0.15349568,  1.20005909],
       [ 1.07781943, -0.96957085,  1.36499951,  0.44742835,  0.54339733],
       [ 2.5230999 , -0.76302595, -1.80333774, -0.08517785, -0.76974948],
       [-0.31686915,  2.06041436, -1.50256588,  0.46805087,  0.12862271]])

In [ ]:
# sd.mean()
# sd.std()

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(1,100)

74

In [ ]:
np.random.randint(1,100,10)

array([70, 62, 11, 27, 44, 47,  8, 75, 16, 97])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

## Reshape
Returns an array containing the same data with a new shape.

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [ ]:
ranarr.max()

49

In [ ]:
ranarr.argmax()

4

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.argmin()

5

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
arr.shape

(25,)

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [ ]:
arr.dtype

dtype('int64')

Indexing and Slicing

In [25]:
a = np.array([10,20,30,40,50])

a[0]

10

In [26]:
a[-1]

50

In [27]:
a[1:4]

array([20, 30, 40])

In [4]:
a = np.array([
[1,2,3],
[4,5,6],
[7,8,9]
])

a[0,1]
a[:,1]
a[1,:]

array([4, 5, 6])

Broadcasting

In [5]:
a = np.array([1,2,3])
b = 10

a + b

array([11, 12, 13])

In [6]:
a = np.array([
[1,2,3],
[4,5,6]
])

b = np.array([10,20,30])

a + b

array([[11, 22, 33],
       [14, 25, 36]])

Vectorized Operations

Instead of loops:

In [9]:
# Bad Way

arr = np.array([
    [1,2,3],
    [4,5,6]
])


result = []
for i in arr:
    result.append(i * 2)

result

[array([2, 4, 6]), array([ 8, 10, 12])]

In [10]:
arr * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [11]:
np.sqrt(arr)
np.log(arr)
np.exp(arr)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

Aggregation

In [12]:
a = np.array([1,2,3,4,5])

np.sum(a)
np.mean(a)
np.std(a)
np.min(a)
np.max(a)

5

In [13]:
np.mean([1,2,3,4])

2.5

Axis Operations

In [14]:
a = np.array([
[1,2,3],
[4,5,6]
])
np.sum(a, axis=0)

array([5, 7, 9])

In [15]:
np.sum(a, axis=1)

array([ 6, 15])

Matrix Operations

In [18]:
A = np.array([
[1,2],
[3,4]
])

B = np.array([
[5,6],
[7,8]
])

In [19]:
A * B

array([[ 5, 12],
       [21, 32]])

In [21]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

Random Number Generation

In [22]:
np.random.rand(3)
np.random.randn(3)
np.random.randint(0,10,5)

array([0, 9, 3, 0, 0])

In [23]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

# Great Job!